name: Deploy to Ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code on runner machine
        uses: actions/checkout@v4

      - name: Run some commands
        run: |
          ls -al
          whoami
          pwd

      - name: Copy files to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "./"
          target: "/home/ubuntu/app"

      - name: Move files to /var/www/html
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/index.html/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html


