name : Deploy to Ec2

on:
  push:
    branches:
       - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: run some commands

      - name: copy files to EC2  
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOSt }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.password }}
          port: ${{ secrets.port }}
          source: ./
          target: /root/home/ubuntu
